# Docker Compose file for setting up a PostgreSQL service.
services:
  postgres:

    image: postgres:15

    container_name: my_postgres_db

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    # allows you to connect to the database using localhost:5432.
    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

      - ./init:/docker-entrypoint-initdb.d

      - ./data:/data

    restart: always

volumes:
  postgres-data:
