services:
  postgres:
    build: .  # Builds from local Dockerfile
    container_name: my_postgres_db
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network
    healthcheck:
      test: PGPASSWORD=${POSTGRES_PASSWORD} psql -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c "SELECT 1"
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    env_file: .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    networks:
      - app-network
    depends_on:
        postgres:
          condition: service_healthy

volumes:
  postgres-data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge
